platform :ios, '8.0'
pod 'AFNetworking'
pod 'UIImageView-Letters'
pod 'JVFloatingDrawer'
pod 'SVProgressHUD'
pod 'STKWebKitViewController'
pod 'DFImageManager'
pod 'PromiseKit'
pod 'PromiseKit-AFNetworking'